/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'Jeff Registre' at '9/20/15 3:59 PM' with Gradle 2.7
 *
 * @author Jeff Registre, @date 9/20/15 3:59 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
