/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'Jeff Registre' at '10/22/15 7:31 PM' with Gradle 2.7
 *
 * @author Jeff Registre, @date 10/22/15 7:31 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
